export enum ConversationState {
  INITIAL = 'INITIAL',
  COLLECTING_DETAILS = 'COLLECTING_DETAILS',
  CONFIRMING_DRAFT = 'CONFIRMING_DRAFT',
  READY_FOR_RFQ = 'READY_FOR_RFQ',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
